### ISSUE TITLE
Display problem with bootstrap 3 theme

### ISSUE THREAD

**Issue by tuxillo** [chtiland/dokuwiki_plugin_konsole#10]
Hi,

It seems there is some sort of display problem with bootstrap 3 theme:

![image](https://cloud.githubusercontent.com/assets/130578/15213471/c94c0ab6-1847-11e6-8411-58119dbe97d8.png)

Cheers,
Antonio Huete

**Comment by chtiland** [comment]
Working on it ;) Thanks for report
