### ISSUE TITLE
Ne fonctionne pas.

### ISSUE THREAD

**Issue by PoseidonFR** [chtiland/dokuwiki_plugin_konsole#15]
Bonjour,
Ne connaissant pas Dokuwiki, je me dis que ça doit venir de moi sur l'installation du plugin.
Mon soucis est que ça ne fonctionne pas du tout.

Dans l'éditeur, voilà le test :

```
<konsole>
Terminal utilisateur
</konsole>
```

Une fois le fichier enregistré, je n'ai que ça en texte :

USER
Terminal utilisateur 

Je n'obtiens pas la fenêtre comme je devrais l'avoir. Merci par avance pour l'aide apportée.

**Comment by chtiland** [comment]
Bonjour,

Je ne rencontre pas de soucis avec la dernière version de Dokuwiki. La console s'affiche correctement.
Est-ce que votre Dokuwiki est accessible ?

Avez-vous essayé de vider le cache de votre navigateur, ainsi que celui de Dokuwiki (data/cache/) ?

Si vous avez installé manuellement en local (en décompressant l'archive), sur quel type d'environnement ? Si un serveur sous Linux, les permissions sur les répertoires et les fichiers sont-elles correctes ?

**Comment by PoseidonFR** [comment]
Bonjour,
Merci pour la réponse rapide. J'ai trouvé la solution, le soucis provenait d'un skin qui n'était apparemment pas compatible.

Encore merci

**Comment by PoseidonFR** [comment]
Désoler, j'ai pas pensé à noter et j'ai viré tous les skins de test. C'était une étape de test seulement alors j'ai rien gardé. Désoler.

**Comment by chtiland** [comment]
Y'a pas de soucis !

Merci et bonnes fêtes de fin d'année.

**Comment by PoseidonFR** [comment]
Merci également ;)
